// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZMoMgjbdMbbIo1PbjUxkOEthgLVed0_c',
    appId: '1:926418909513:web:2c367a4227335aa1bb8298',
    messagingSenderId: '926418909513',
    projectId: 'misproject-6f3e3',
    authDomain: 'misproject-6f3e3.firebaseapp.com',
    storageBucket: 'misproject-6f3e3.appspot.com',
    measurementId: 'G-GS1B7SLBRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_9n5seX2_riOw6y_pPNA0WixFbSDROk',
    appId: '1:926418909513:android:2f219cdee23c2545bb8298',
    messagingSenderId: '926418909513',
    projectId: 'misproject-6f3e3',
    storageBucket: 'misproject-6f3e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1HZ3h2yPTyUi0-T3FXyZ61cbL2tYTokA',
    appId: '1:926418909513:ios:86ebf60e5279a43dbb8298',
    messagingSenderId: '926418909513',
    projectId: 'misproject-6f3e3',
    storageBucket: 'misproject-6f3e3.appspot.com',
    iosBundleId: 'com.example.misproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1HZ3h2yPTyUi0-T3FXyZ61cbL2tYTokA',
    appId: '1:926418909513:ios:abf9bc6b457f755dbb8298',
    messagingSenderId: '926418909513',
    projectId: 'misproject-6f3e3',
    storageBucket: 'misproject-6f3e3.appspot.com',
    iosBundleId: 'com.example.misproject.RunnerTests',
  );
}
